import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import Head from "next/head";
import { useState } from "react";

const index = () => {
  const [show, setShow] = useState(false);

  return (
    <>
      <Head>
        <title>Admin Dashboard : Transactions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section dmSans">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-7">
            <Topbar pageName={"Transactions"} show={show} setShow={setShow} />
            <div className="grid md:grid-cols-1 my-0 mx-4 ">
              <div className="overflow-x-auto">
                <table className="table-auto w-full  mt-10 font-normal">
                  <thead className="text-white">
                    <tr className="text-black flex md:flex-row flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
                      <th className="p-3 text-left text-[#717D82]">Date</th>
                      <th className="p-3 text-left text-[#717D82]">
                        Transaction ID
                      </th>
                      <th className="p-3 text-left text-[#717D82]">
                        Description
                      </th>
                      <th className="p-3 text-left text-[#717D82]">
                        Payment Method
                      </th>
                      <th className="p-3 text-left text-[#717D82]">Remark</th>

                      <th className="p-3 text-left text-[#717D82]">Amount</th>
                      <th className="p-3 text-left text-[#717D82]">Charge</th>
                      <th className="p-3 text-left text-[#717D82]">Action</th>
                    </tr>
                  </thead>
                  <tbody className="">
                    {/* <TableRow /> */}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default index;

const TableRow = ({ data }) => {
  return (
    <tr className="flex md:flex-row flex-no-wrap sm:table-row mb-2 sm:mb-0">
      <td className="text-[#464F53] font-normal  p-3">27-Jan-2023</td>
      <td className="text-[#464F53] font-normal   p-3 truncate">PDF343gfmf</td>
      <td className=" text-[#464F53] font-normal  p-3 ">Pay by Bkash</td>
      <td className="   p-3 text-green-500 font-bold">
        <button className="bg-black px-2 py-1 rounded-md text-[12px] text-white">
          Order Placed
        </button>
      </td>
      <td className=" p-3 text-[#FF6A6A]">-0 USD</td>
      <td className="text-[#464F53] font-normal p-3 ">10 USD</td>

      <td className="   p-3 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer flex items-center">
        <button className="bg-[#7A8489] px-2 py-1 rounded-md text-[12px] text-white">
          Approve
        </button>
        <button className="bg-[#C34747] mx-2 px-2 py-1 rounded-md text-[12px] text-white">
          Cancel
        </button>
        <button className="bg-[#47C363] px-2 py-1 rounded-md text-[12px] text-white">
          Completed
        </button>
      </td>
    </tr>
  );
};
