import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

const index = (props) => {
  const router = useRouter();
  const { permission } = router.query;
  const [isChecked, setIsChecked] = useState(false);

  const handleCheckboxChange = (event) => {
    setIsChecked(event.target.checked);
  };

  console.log('isChecked', isChecked)

  const i = [
    3, 34, 34, 434, 34, 34, 343, 434, 34, 34, 34, 343, 434, 343, 43, 2, 2, 2, 2,
    2, 3, 4, 5, 6, 6, 1, 23, 3, 4343, 343, 43, 6, 6, 1, 23, 3, 4343, 343,
  ];
  const [show, setShow] = useState(false);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-10">
            <Topbar pageName={"Manage Roles"} show={show} setShow={setShow} />
            <section className="main-right lg:ml-[38px] ">
              <h1 className="md:text-[37px] text-[18px] text-center md:text-start text-[#1A1A1A] font-semibold py-3 px-2">
                Edit Role Permissions : Moderator
              </h1>

              <form
                action=""
                className="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-1 gap-8 px-6"
              >
                {i.map((id, index) => {
                  return (
                    <Card
                      key={index}
                      data={index}
                      handleCheckboxChange={handleCheckboxChange}
                      isChecked={isChecked}
                    />
                  );
                })}
              </form>
            </section>
          </div>
        </section>
      </main>
    </>
  );
};

export default index;

const Card = ({ isChecked, handleCheckboxChange }) => {
  return (
    <div className="flex role-card items-center justify-between p-4">
      <h1 className="text-[15px] font-medium">Dashboard Info</h1>
      <label className="switch">
        <input
          type="checkbox"
          checked={isChecked}
          onChange={handleCheckboxChange}
        />
        <span className="slider round" />
      </label>
    </div>
  );
};
