import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import useUser from "@/Hooks/useUser";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

const index = () => {
  const [show, setShow] = useState(false);
  const [users] = useUser();
  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-10">
            <Topbar pageName={"Manage Roles"} show={show} setShow={setShow} />
            <section className="main-right ml-[38px] ">
              <div className="container">
                <table className="w-full flex flex-row flex-no-wrap sm:bg-white rounded-lg overflow-hidden mt-10">
                  <thead className="text-white bg-[#e2f0f74f]">
                    <tr className="text-black flex flex-col flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
                      <th className="p-3 text-left text-[#717D82]">SI</th>
                      <th className="p-3 text-left text-[#717D82]">Email</th>
                      <th className="p-3 text-left text-[#717D82]">Name</th>
                      <th className="p-3 text-left text-[#717D82]">Role</th>

                      <th className="p-3 text-left text-[#717D82]">Action</th>
                    </tr>
                  </thead>
                  <tbody className="flex-1 sm:flex-none">
                    {users.map((user, i) => {
                      return (
                        <tr
                          key={i}
                          className="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0"
                        >
                          <td className="text-[#464F53]   font-normal   p-3">
                            {i + 1}
                          </td>
                          <td className="text-[#464F53]   font-normal   p-3 truncate">
                            {user?.email}
                          </td>
                          <td className="text-[#464F53]   font-normal   p-3 ">
                            {user?.name}
                          </td>
                          <td className="text-[#464F53]   font-normal   p-3 ">
                            {user?.role}
                          </td>
                          <td className=" font-normal  p-3 text-red-400  cursor-pointer">
                            <button className="bg-[#6777EF] px-3 py-2 rounded-md text-[12px] text-white">
                              <Link
                                href={`/users/manage/permission/${user?.email}`}
                              >
                                Permissions
                              </Link>
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </section>
          </div>
        </section>
      </main>
    </>
  );
};

export default index;
