import Head from "next/head";
import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import { useState } from "react";

export default function Home({}) {
  const [show, setShow] = useState(false);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dmSans">
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-10">
            <Topbar pageName={"TopUp"} show={show} setShow={setShow} />

            <section className="main-right">
              <div className="px-10 pt-6">
                <h2
                  className="flex items-center text-[
                    19px] font-bold text-black"
                >
                  <span>Current Balance</span>
                  <span className="ml-[140px]">$456</span>
                </h2>
                <h2
                  className="flex items-center text-[
                    19px] font-bold text-[#8756EF] mt-[22px]"
                >
                  <span>Pending Balance</span>
                  <span className="ml-[140px]">$456</span>
                </h2>
                <div
                  className="flex items-center text-[
                    19px] font-bold text-black mt-[22px]"
                >
                  <h4>Pending Balance</h4>
                  <div className="ml-[140px] flex">
                    <input type="checkbox" className="" />
                    <h3 className="pl-3">Cash</h3>
                  </div>
                </div>
                <div
                  className="lg:flex items-center text-[
                    19px] font-medium text-[#7A8489] mt-[16px]"
                >
                  <h4>Amount to Add</h4>
                  <div className="lg:ml-[180px] flex">
                    <input
                      type="number"
                      className="border bg-white rounded-md border-[#7A8489] lg:w-[228px] w-full px-2 py-1"
                    />
                  </div>
                </div>

                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[16px]"
                >
                  <h4 className="font-medium mb-2 lg:mb-0">Paid To</h4>
                  <div className="lg:ml-[230px]">
                    <div className="flex">
                      <div className="flex items-center">
                        <input type="checkbox" className="" />
                        <h3 className="pl-3">Noman</h3>
                      </div>
                      <div className="flex items-center ml-3">
                        <input type="checkbox" className="" />
                        <h3 className="pl-3">Alif</h3>
                      </div>
                      <div className="flex items-center ml-3">
                        <input type="checkbox" className="" />
                        <h3 className="pl-3">Meheraj</h3>
                      </div>
                    </div>
                    <div className="mt-4">
                      <button className="px-[32px] rounded-lg py-[10px] text-white  bg-[#47C363]">
                        Confirm
                      </button>
                    </div>
                  </div>
                </div>
                {/* Cash payment End  */}
                <div className="lg:pl-[274px] mt-20">
                  <div className="flex">
                    <input type="checkbox" className="" />
                    <h3 className="pl-3 font-bold">Mobile Banking</h3>
                  </div>
                  {/* options  */}
                  <div className="flex mt-3 items-center">
                    <div className="flex">
                      <input type="checkbox" className="" />
                      <h3 className="pl-3 font-bold">Bkash</h3>
                    </div>
                    <div className="flex px-5">
                      <input type="checkbox" className="" />
                      <h3 className="pl-3 font-bold">Nagad</h3>
                    </div>
                    <div className="flex">
                      <input type="checkbox" className="" />
                      <h3 className="pl-3 font-bold">Rocket</h3>
                    </div>
                  </div>
                  {/* {"Options"} */}
                  <div className="flex mt-3 items-center">
                    <div className="flex">
                      <input type="checkbox" className="" />
                      <h3 className="pl-3 font-bold">Upay</h3>
                    </div>
                    <div className="flex px-5">
                      <input type="checkbox" className="" />
                      <h3 className="pl-3 font-bold">mCash</h3>
                    </div>
                    <div className="flex">
                      <input type="checkbox" className="" />
                      <h3 className="pl-3 font-bold">Sure Cash</h3>
                    </div>
                  </div>
                </div>

                {/* Payment Options End  */}
                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Ammount To Add</h4>
                  <div className="lg:ml-[182px] mt-2 lg:mt-0">
                    <input
                      type="number"
                      className="border bg-white rounded-md border-[#7A8489] lg:w-[228px] w-full px-2 py-1"
                      placeholder="334,343/="
                    />
                  </div>
                </div>

                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Customer Phone Number</h4>
                  <div className="lg:ml-[125px] mt-2 lg:mt-0">
                    <input
                      type="number"
                      className="border bg-white rounded-md border-[#7A8489] w-full lg:w-[228px] px-2 py-1"
                    />
                  </div>
                </div>
                <div
                  className="lg:flex items-center text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Paid To</h4>
                  <div className="lg:ml-[250px] lg:flex items-cente mt-2 lg:mt-0">
                    <select
                      type=""
                      className="border bg-white rounded-md border-[#7A8489] w-full lg:w-[228px] px-2 py-1 font-medium text-[14px]"
                    >
                      <option value="">Please Select</option>
                      <option value="">Please Select</option>
                      <option value="">Please Select</option>
                    </select>

                    <div className="border flex flex-col items-center border-gray-400 lg:ml-3 py-2 mt-3 lg:mt-0  rounded-md font-medium">
                      <div className="flex items-center  px-3">
                        <input type="checkbox" className="" />
                        <h3 className="pl-3">+880343432323</h3>
                      </div>
                      <div className="w-full my-[2px] h-[2px] bg-gray-300"></div>
                      <div className="flex items-center  px-4">
                        <input type="checkbox" className="" />
                        <h3 className="pl-3">+880343432323</h3>
                      </div>
                    </div>
                  </div>
                </div>

                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Transaction Id</h4>
                  <div className="lg:ml-[206px] mt-2 lg:mt-0 flex flex-col">
                    <div className="lg:flex  items-center">
                      <input
                        type=""
                        className="border bg-white rounded-md border-[#7A8489] w-full lg:w-[228px] px-2 py-1 font-medium"
                        placeholder="Transaction Id"
                      />
                      <p className="px-3 py-2 lg:py-0">or</p>
                      <label
                        htmlFor="file-attach"
                        className="border bg-white rounded-md border-[#7A8489] w-[228px] px-2 py-1 font-medium"
                      >
                        Attach ScreenShoot
                      </label>
                      <input
                        type="file"
                        className="hidden"
                        id="file-attach"
                        placeholder=""
                      />
                    </div>
                    <div className="mt-10">
                      <button className="px-[32px] rounded-lg py-[10px] text-white  bg-[#47C363]">
                        Confirm
                      </button>
                    </div>
                  </div>
                </div>

                {/* internet Banking  */}
                {/* internet Banking  */}

                <div className="lg:pl-[274px] mt-20">
                  <div className="flex">
                    <input type="checkbox" className="" />
                    <h3 className="pl-3 font-bold">Internet Banking</h3>
                  </div>
                </div>
                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Ammount To Add</h4>
                  <div className="lg:ml-[182px] mt-2 lg:mt-0">
                    <input
                      type="number"
                      className="border bg-white rounded-md border-[#7A8489] lg:w-[228px] w-full px-2 py-1"
                      placeholder="334,343/="
                    />
                  </div>
                </div>

                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4 className="mb-2 lg:mb-0">Select Bank</h4>
                  <div className="lg:ml-[220px] flex flex-col justify-center">
                    <input
                      type="text"
                      className="border bg-white rounded-md border-[#7A8489] lg:w-[530px] w-full px-2 py-2 font-medium text-[14px]"
                      placeholder="Search (Ex: Dhaka bank , City bank )"
                    />
                    <select
                      type=""
                      className="border bg-white rounded-md border-[#7A8489] lg:w-[530px] w-full px-2 py-2 font-medium text-[14px] mt-3"
                    >
                      <option value="">Select From List</option>
                      <option value="">Dhaka Bank</option>
                      <option value="">City Bank</option>
                      <option value="">Eastern Bank</option>
                      <option value="">Prime Bank</option>
                      <option value="">DBBL</option>
                      <option value="">SIBL</option>
                      <option value="">HSBC</option>
                    </select>
                  </div>
                </div>

                {/* Select Bank End Here  */}
                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Account Number</h4>
                  <div className="lg:ml-[186px] mt-2 lg:mt-0">
                    <input
                      type="number"
                      className="border bg-white rounded-md border-[#7A8489] w-full lg:w-[228px] px-2 py-1"
                      placeholder="3434 3434 3434 3434"
                    />
                  </div>
                </div>

                {/* Upload Payment Proof  */}
                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Upload Payment Proof</h4>
                  <div className="lg:ml-[143px] flex flex-col mt-3 lg:mt-0">
                    <div>
                      <label
                        htmlFor="file-attach"
                        className="border bg-white rounded-md border-[#7A8489] w-[228px] px-3 py-2 font-medium"
                      >
                        Attach ScreenShoot
                      </label>
                      <input
                        type="file"
                        className="hidden"
                        id="file-attach"
                        placeholder=""
                      />
                    </div>

                    <div className="mt-10">
                      <button className="px-[32px] rounded-lg py-[10px] text-white  bg-[#47C363]">
                        Confirm
                      </button>
                    </div>
                  </div>
                </div>

                {/* international Banking  */}
                {/* international Banking  */}

                <div className="lg:pl-[274px] mt-20">
                  <div className="flex">
                    <input type="checkbox" className="" />
                    <h3 className="pl-3 font-bold">International Banking</h3>
                  </div>
                </div>
                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Ammount To Add</h4>
                  <div className="lg:ml-[182px] mt-2 lg:mt-0">
                    <input
                      type="number"
                      className="border bg-white rounded-md border-[#7A8489] w-full lg:w-[228px] px-2 py-1"
                      placeholder="334,343/="
                    />
                  </div>
                </div>
                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Select Payment Method</h4>
                  <div className="lg:ml-[137px] text-black mt-2 lg:mt-0">
                    <div className="flex mt-3 items-center">
                      <div className="flex">
                        <input type="checkbox" className="" />
                        <h3 className="pl-3 font-bold">Wise</h3>
                      </div>
                      <div className="flex px-5">
                        <input type="checkbox" className="" />
                        <h3 className="pl-3 font-bold">Payoneer</h3>
                      </div>
                    </div>
                  </div>
                </div>
                {/* Select Bank End Here  */}
                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Account Email</h4>
                  <div className="lg:ml-[201px] mt-2 lg:mt-0">
                    <input
                      type="number"
                      className="border bg-white rounded-md border-[#7A8489] w-full lg:w-[228px] px-2 py-1"
                      placeholder="example@example.com"
                    />
                  </div>
                </div>
                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Customer Account Email</h4>
                  <div className="lg:ml-[130px] mt-2 lg:mt-0">
                    <input
                      type="number"
                      className="border bg-white rounded-md border-[#7A8489] w-full lg:w-[228px] px-2 py-1"
                      placeholder="example@example.com"
                    />
                  </div>
                </div>
                {/* Upload Payment Proof  */}
                <div
                  className="lg:flex items-start text-[
                    19px] font-medium text-[#7A8489] mt-[26px]"
                >
                  <h4>Upload Payment Proof</h4>
                  <div className="lg:ml-[143px] flex flex-col mt-2 lg:mt-0">
                    <div>
                      <label
                        htmlFor="file-attach"
                        className="border bg-white rounded-md border-[#7A8489] w-[228px] px-3 py-2 font-medium"
                      >
                        Attach ScreenShoot
                      </label>
                      <input
                        type="file"
                        className="hidden"
                        id="file-attach"
                        placeholder=""
                      />
                    </div>

                    <div className="mt-10">
                      <button className="px-[32px] rounded-lg py-[10px] text-white  bg-[#47C363]">
                        Confirm
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </section>
      </main>
    </>
  );
}
