import Head from "next/head";
import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import StatisticsCard from "@/Components/Shared/Homepage/StatisticsCard";
import { statistics } from "@/Components/dummy";
import OverallSales from "@/Components/Shared/Homepage/OverallSales";
import RecentOrder from "@/Components/Shared/Homepage/RecentOrder";
import Analytic from "@/Components/Shared/Homepage/Analytic";
import Satisfaction from "@/Components/Shared/Homepage/Satisfaction";
import CustomarReviwe from "@/Components/Shared/Homepage/CustomarReviwe";
import { useState } from "react";
// import "tw-elements";

export default function Home({}) {
  const [show, setShow] = useState(false);
  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-10">
            <Topbar pageName={"Dashboard"} show={show} setShow={setShow} />

            <section className="main-right lg:ml-[38px] lg:px-0 px-3 grid grid-cols-12 gap-5">
              <div className="lg:col-span-8 md:col-span-12">
                <div className="ststistics w-full gap-3 mt-[53px] justify-between">
                  {statistics.map((st, index) => {
                    return <StatisticsCard key={index} data={st} />;
                  })}
                </div>
                <OverallSales />
                <RecentOrder />
              </div>

              <div className="col-span-4 mt-10 lg:px-4">
                <Analytic />
                <Satisfaction />
                <CustomarReviwe />
              </div>
            </section>
          </div>
        </section>
      </main>
    </>
  );
}
