import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import Head from "next/head";
import { useState } from "react";

const index = () => {
  const [show, setShow] = useState(false);

  return (
    <>
      <Head>
        <title>Admin Dashboard : Transactions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section dmSans">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-7">
            <Topbar pageName={"Customer Order"} show={show} setShow={setShow} />
            <section className="main-right ml-[38px] ">
              <div className="px-3">
                <table className="w-full flex flex-row flex-no-wrap sm:bg-white rounded-lg overflow-hidden mt-10 font-normal">
                  <thead className="text-white">
                    <tr className="text-black flex flex-col flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0 h-[59.99px]">
                      <th className="p-3 h-full border-2 text-left text-[#717D82] ">
                        <input type="checkbox" className=" w-full" />
                      </th>
                      <th className=" border-2 p-3 text-left text-[#717D82]">
                        User
                      </th>
                      <th className="p-3  text-center border-2 text-[#717D82]">
                        Order ID
                      </th>
                      <th className="p-3 text-center  border-2 text-[#717D82]">
                        Service/Price
                      </th>
                      <th className="p-3 text-center border-2 text-[#717D82]">
                        Link/QTY
                      </th>
                      <th className="p-3 text-center  border-2 text-[#717D82]">
                        Counter / Api Response
                      </th>
                      <th className="p-3 text-center  border-2 text-[#717D82]">
                        Status
                      </th>
                      <th className="p-3 text-center  border-2 text-[#717D82]">
                        Order at
                      </th>
                      <th className="p-3 text-center  border-2 text-[#717D82]">
                        Action
                      </th>
                    </tr>
                  </thead>
                  <tbody className="flex-1 sm:flex-none">
                    <TableRow />
                    <TableRow />
                    <TableRow />
                    <TableRow />
                    <TableRow />
                    <TableRow />
                    <TableRow />
                  </tbody>
                </table>
              </div>
            </section>
          </div>
        </section>
      </main>
    </>
  );
};

export default index;

const TableRow = ({ data }) => {
  return (
    <tr className="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0">
      <td className="text-[#464F53]  border-2 font-normal  p-3">
        <input type="checkbox" className="p-2 w-full" />
      </td>
      <td className="text-[#464F53]  border-2 font-normal  p-3">user</td>
      <td className="text-[#464F53] text-center  border-2 font-normal  p-3">
        45453
      </td>
      <td className="text-[#464F53]  border-2 font-normal p-3">
        <div className="flex flex-col items-center py-1">
          <h5>Facebook Page Likes (23k)</h5>
          <div className="hr my-3"></div>
          <p className="text-[#465EED]">Price : 0.21 USD</p>
        </div>
      </td>
      <td className="text-[#464F53]  border-2 font-normal p-3">
        <div className="flex flex-col items-center py-1">
          <h5>
            <a className="text-[#465EED]" href="/">
              https://examplewebsite.com
            </a>
          </h5>
          <div className="hr my-3"></div>
          <p>Quantity: 100</p>
        </div>
      </td>
      <td className="text-[#464F53]  border-2 font-normal p-3">
        <div className="flex flex-col items-center py-1">
          <h5 className="text-[#47C363]">Start Counter: 0</h5>
          <h5 className="text-[#C34747]">Remainings: 5</h5>
          <div className="hr my-3"></div>
          <p className="text-[#465EED]">Quantity less then minimal 100</p>
        </div>
      </td>
      <td className="border-2 px-5 text-center">
        <button className="bg-[#3ABAF4] px-6 py-1 rounded-md text-[12px] text-white">
          Buy
        </button>
      </td>
      <td className="border-2"></td>
      <td className="border-2"></td>
    </tr>
  );
};
