import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";

const index = () => {
  const router = useRouter();
  const { user } = router.query;
  const [show, setShow] = useState(false);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>
          <div className="right-side pb-10 ">
            <Topbar pageName={"Profile"} show={show} setShow={setShow} />
            <section className="main-right   min-h-screen bg-[#E6E6E6]">
              <div className="pt-[75px] md:pl-[50px] pl-5 md:flex items-center">
                <div className="w-[281.21px] h-[281.21px] rounded-full bg-white overflow-hidden">
                  <Image
                    width={280}
                    height={280}
                    src={"/images/profile.jpeg"}
                    alt=""
                  />
                </div>
                <div className="md:ml-[100px] mt-5">
                  <p>Account 100% Complete</p>
                </div>
              </div>

              <section className="grid grid-cols-12 px-5 md:pl-[50px] mt-[26px] pb-10">
                <div className="lg:col-span-3 col-span-12">
                  <h1 className="text-[28.27px] font-medium">Super Admin</h1>
                  <div className=" bg-gray-600 h-[2px] mt-[15px] "></div>
                </div>

                <form
                  action=""
                  className="lg:col-span-10 col-span-12 gap-5 grid grid-cols-12 mt-5 w-full"
                >
                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">Name</label>
                    <input
                      type="text"
                      className="border mt-2 border-black w-full rounded-md px-3 font-medium py-1"
                      placeholder="Name"
                      name="name"
                    />
                  </div>

                  <div className="col-span-12">
                    <label className="text-[16.27px] font-medium">Adress</label>
                    <input
                      type="text"
                      name="adress"
                      className="border mt-2 border-black w-full rounded-md px-3 font-medium py-1"
                      placeholder="Adress"
                    />
                  </div>
                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">
                      Phone Number
                    </label>
                    <div className="md:flex lg:flex block items-center mt-2">
                      <input
                        type="text"
                        name="phoneNumber"
                        className="border  border-black w-full rounded-md px-3 font-medium py-1"
                        placeholder="Phone Number"
                      />
                      <button className="bg-[#47C363] px-[23px] py-[6px] text-[white] font-medium md:ml-2 mt-1 rounded-lg">
                        Verified
                      </button>
                    </div>
                  </div>

                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">
                      Behance
                    </label>
                    <input
                      type="text"
                      name="behance"
                      className="border mt-2 border-black w-full rounded-md px-3 font-medium py-1"
                      placeholder="Behance"
                    />
                  </div>

                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">
                      Whatsapp Number
                    </label>
                    <div className="md:flex lg:flex block items-center justify-between mt-2">
                      <input
                        type="text"
                        name="whatsappNumber"
                        className="border  border-black w-full rounded-md px-3 font-medium py-1"
                        placeholder="Whatsapp Number"
                      />
                      <button className="bg-[#7A8489] w-[122px] px-[8px] py-[6px] text-[white] font-medium md:ml-2 mt-1 rounded-lg flex">
                        Verify Now
                      </button>
                    </div>
                  </div>
                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">
                      Company Website
                    </label>
                    <input
                      type="text"
                      name="we-name"
                      className="border mt-2 border-black w-full rounded-md px-3 font-medium py-1"
                      placeholder="Company Website"
                    />
                  </div>
                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">Email</label>
                    <div className="md:flex lg:flex block items-center justify-between mt-2">
                      <input
                        type="text"
                        name="email"
                        className="border  border-black w-full rounded-md px-3 font-medium py-1"
                        placeholder="Email"
                      />
                      <button className="bg-[#7A8489] w-[122px] px-[8px] py-[6px] text-[white] font-medium md:ml-2 mt-1 rounded-lg flex">
                        Verify Now
                      </button>
                    </div>
                  </div>

                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">NID</label>
                    <div className="md:flex lg:flex block items-center justify-between mt-2">
                      <input
                        type="text"
                        name="nid"
                        className="border  border-black w-full rounded-md px-3 font-medium py-1"
                        placeholder="Nid"
                      />
                      <label
                        htmlFor="nid"
                        className="border border-black w-[145.02px] px-[8px] py-[6px] text-black font-medium md:ml-2 mt-1 rounded-lg flex items-center"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={1.5}
                          stroke="currentColor"
                          className="w-4 h-4 mr-1"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13"
                          />
                        </svg>
                        Attach File
                      </label>
                      <input type="file" id="nid" className="hidden" />
                    </div>
                  </div>
                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">
                      Linkdin Profile
                    </label>
                    <input
                      type="text"
                      name="nid"
                      className="border mt-2 border-black w-full rounded-md px-3 font-medium py-1"
                      placeholder="Linkdin Profile"
                    />
                  </div>

                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">TIN</label>
                    <div className="md:flex lg:flex block items-center justify-between mt-2">
                      <input
                        type="text"
                        name="tin"
                        className="border  border-black w-full rounded-md px-3 font-medium py-1"
                        placeholder="TIn"
                      />
                      <label
                        htmlFor="nid"
                        className="border border-black w-[145.02px] px-[8px] py-[6px] text-black font-medium md:ml-2 mt-1 rounded-lg flex items-center"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={1.5}
                          stroke="currentColor"
                          className="w-4 h-4 mr-1"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13"
                          />
                        </svg>
                        Attach File
                      </label>
                      <input type="file" id="nid" className="hidden" />
                    </div>
                  </div>
                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">
                      Github Profile
                    </label>
                    <input
                      type="text"
                      name="nid"
                      className="border mt-2 border-black w-full rounded-md px-3 font-medium py-1"
                      placeholder="Github Profile"
                    />
                  </div>
                  <div className="lg:col-span-6 col-span-12">
                    <label className="text-[16.27px] font-medium">BIN</label>
                    <div className="md:flex lg:flex block items-center justify-between mt-2">
                      <input
                        type="text"
                        name="bin"
                        className="border  border-black w-full rounded-md px-3 font-medium py-1"
                        placeholder="BIN"
                      />
                      <label
                        htmlFor="nid"
                        className="border border-black w-[145.02px] px-[8px] py-[6px] text-black font-medium md:ml-2 mt-1 rounded-lg flex items-center"
                      >
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 24 24"
                          strokeWidth={1.5}
                          stroke="currentColor"
                          className="w-4 h-4 mr-1"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13"
                          />
                        </svg>
                        Attach File
                      </label>
                      <input type="file" id="nid" className="hidden" />
                    </div>
                  </div>

                  <div className="col-span-12 flex justify-end items-center mt-5">
                    <button className="bg-[#465EED] py-[10px] px-[50px] rounded-lg text-[16px] text-white">
                      EDIT
                    </button>
                    <button className="bg-[#47C363] ml-10 py-[10px] px-[50px] rounded-lg text-[16px] text-white">
                      SAVE
                    </button>
                  </div>
                </form>
              </section>
            </section>
          </div>
        </section>
      </main>
    </>
  );
};

export default index;
