import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import { addAccountReqDB } from "Database/addAccountReqDB";
import Head from "next/head";
import { useState } from "react";

const AddAccount = () => {
  const [show, setShow] = useState(false);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-10">
            <Topbar
              pageName={"Add Accounts "}
              color={"#7845E7"}
              show={show}
              setShow={setShow}
            />
            <div className="grid md:grid-cols-1 my-0 mx-4">
              <div className="md:flex block  items-center justify-between pr-10 mt-5">
                <button className="bg-[#DBDEE4] md:text-[16px] text-[12px] font-bold border border-[#7A8489] rounded-xl px-[20px] py-[12px]">
                  Crete Ad Account
                </button>
                <button className="bg-[#DBDEE4] flex items-center border border-[#7A8489] md:text-[16px] text-[12px] mt-3 md:mt-0 font-bold rounded-xl px-[20px] py-[12px]">
                  All Ad Account
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className="w-5 h-5 ml-2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M19.5 8.25l-7.5 7.5-7.5-7.5"
                    />
                  </svg>
                </button>
              </div>

              <div className="overflow-x-auto">
                <table className="table-auto w-full  mt-10 font-normal">
                  <thead className="text-white">
                    <tr className="text-black flex md:flex-row flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
                      <th className="p-3 text-left text-[#717D82]">Date</th>
                      <th className="p-3 text-left text-[#717D82]">
                        Add Account Name
                      </th>
                      <th className="p-3 text-left text-[#717D82]">
                        Add Account Number
                      </th>
                      <th className="p-3 text-left text-[#717D82]">
                        Page Name
                      </th>
                      <th className="p-3 text-left text-[#717D82]">Page ID</th>
                      <th className="p-3 text-left text-[#717D82]">Country</th>

                      <th className="p-3 text-left text-[#717D82]">Action</th>
                    </tr>
                  </thead>
                  {/* table ad account requests dynamic data */}
                  {addAccountReqDB.map((ad, i) => {
                    return (
                      <tbody key={i}>
                        <TableRow ad={ad} />
                      </tbody>
                    );
                  })}
                </table>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default AddAccount;

const TableRow = ({ ad }) => {
  const { date, adAccountName, adAccountNumber, pageName, pageID, country } =
    ad;
  return (
    <>
      <tr className="flex md:flex-row flex-no wrap sm:table-row mb-2 sm:mb-0 text-[14px]">
        <td className="text-[#464F53]   font-normal   p-3">{date}</td>
        <td className="text-[#464F53]   font-normal   p-3 truncate">
          {adAccountName}
        </td>
        <td className="text-[#464F53]   font-normal   p-3 ">
          {adAccountNumber}
        </td>
        <td className="text-[#464F53]   font-normal   p-3 ">{pageName}</td>
        <td className="text-[#464F53]   font-normal   p-3 ">{pageID}</td>
        <td className="text-[#464F53]   font-normal   p-3 ">{country}</td>
        <td className=" font-normal  p-3 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer">
          <button className="bg-[#47C363] px-2 py-1 sm:my-1 rounded-md text-[12px] text-white">
            Active
          </button>
          <button className="bg-[#C34747] mx-2 px-2 py-1 sm:my-1 rounded-md text-[12px] text-white">
            Rejected
          </button>
          <button className="bg-[#8756EF] px-2 py-1 sm:my-1 rounded-md text-[12px] text-white">
            Pending
          </button>
        </td>
      </tr>
    </>
  );
};
