import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import Head from "next/head";
import { useState } from "react";

const index = () => {
  const [show, setShow] = useState(false);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>

          <div className="right-side pb-10">
            <Topbar pageName={"Manage User"} show={show} setShow={setShow} />
            <section className="main-right ml-[38px] ">
              <div className="container">
                <table className="w-full flex flex-row flex-no-wrap sm:bg-white rounded-lg overflow-hidden mt-10">
                  <thead className="text-white">
                    <tr className="text-black flex flex-col flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
                      <th className="p-3 text-left text-[#717D82]">Name</th>
                      <th className="p-3 text-left text-[#717D82]">Email</th>
                      <th className="p-3 text-left">Country</th>
                      <th className="p-3 text-left">Status</th>
                      <th className="p-3 text-left">Action</th>
                    </tr>
                  </thead>
                  <tbody className="flex-1 sm:flex-none">
                    <TableRow data={{ status: "active" }} />
                    <TableRow data={{ status: "Inactive" }} />
                    <TableRow data={{ status: "Blocked" }} />
                    <TableRow data={{ status: "active" }} />
                    <TableRow data={{ status: "active" }} />
                    <TableRow data={{ status: "Blocked" }} />
                    <TableRow data={{ status: "active" }} />
                    <TableRow data={{ status: "Inactive" }} />

                    <TableRow data={{ status: "active" }} />
                    <TableRow data={{ status: "active" }} />
                  </tbody>
                </table>
              </div>
            </section>
          </div>
        </section>
      </main>
    </>
  );
};

export default index;

const TableRow = ({ data }) => {
  return (
    <tr className="flex flex-col flex-no wrap sm:table-row mb-2 sm:mb-0">
      <td className="   p-3">John Covv</td>
      <td className="   p-3 truncate">contato@johncovv.com</td>
      <td className="   p-3 ">Bangladesh</td>
      <td className="   p-3 text-green-500 font-bold">
        <button
          className={`${data.status === "active" && "bg-[#47C363]"} 
            ${data.status === "Inactive" && "bg-[#C3BE47]"} 
            ${data.status === "Blocked" && "bg-[#C34747]"} 
            px-2 py-1 rounded-md text-[12px] text-white`}
        >
          {data.status}
        </button>
      </td>

      <td className="   p-3 text-red-400 hover:text-red-600 hover:font-medium cursor-pointer">
        <button className="bg-[#6777EF] px-2 py-1 rounded-md text-[12px] text-white">
          Details
        </button>
      </td>
    </tr>
  );
};
