import Head from "next/head";
import Sidebar from "@/Components/Sidebar/Sidebar";
import Topbar from "@/Components/Topbar";
import { useState } from "react";

export default function Home({}) {
  const [show, setShow] = useState(false);

  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dmSans">
        <section className="main-section">
          <div
            className={`left-side ${
              show
                ? "block lg:relative absolute top-0"
                : "md:hidden lg:block hidden"
            }`}
          >
            <Sidebar setShow={setShow} show={show} />
          </div>
          <div className="right-side pb-10">
            <Topbar
              pageName={"Bill Management"}
              show={show}
              setShow={setShow}
            />
            <div className="px-10 mt-6 lg:flex  items-center justify-between">
              <h1 className="text-[40px]">Mobile Banking</h1>
              <h1 className="text-[26px]">Add Another Account</h1>
            </div>
            <section className="main-right p-7 grid lg:grid-cols-2 grid-cols- grid-cols-2 gap-10">
              <Card />
              <Card />
              <Card />
              <Card />
              <Card />
              <Card />
            </section>
          </div>
        </section>
      </main>
    </>
  );
}

const Card = ({ name, number, fee }) => {
  return (
    <div className="shadow-lg p-5 rounded-lg">
      <div className="flex justify-between items-center">
        <h1 className="text-[28.27px]">{name ? name : "Bkash (Marchent)"} </h1>
        <label className="switch">
          <input type="checkbox" />
          <span className="slider round" />
        </label>
      </div>
      <div className="hr my-2 bg-black"></div>

      <div className="mt-3">
        <label htmlFor="">Number</label>
        <input
          type="text"
          className=" border-gray-700 w-full border-2 mt-2 rounded-md px-3 py-1 mb-5"
          defaultValue={number ? number : "01348343437"}
        />

        <label htmlFor="" className="">
          Fee
        </label>
        <input
          type="text"
          className=" border-gray-700 w-full border-2 mt-2 rounded-md px-3 py-1 mb-5"
          defaultValue={fee ? fee : "3%"}
        />
      </div>
    </div>
  );
};
